---
title: "Breaking into Bicycle Thefts: Rough Work"
author: Haruka Takagi & Arusan Surendiran
date: 2022-11-10
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# ENVIRONMENT SETUP
library(RColorBrewer)
library(extrafont)
library(ggeasy)
library(ggmap)
library(rgeos)
library(ggplot2)
library(rgdal)
library(maptools)
library(ggtext)
library(ggplot2)
library(ggbreak) 
library(patchwork)
library(dplyr)
library(scales)
library(viridis)
library(ggthemes)
library(gridExtra)
library(lubridate)
library(data.table)
library(tidyverse)
library(forcats)
library(ggrepel)
loadfonts(device = "win")
```

```{r, include=FALSE}
# HARUKA DATA PREPARATION
data_bike <- read.csv('data.csv') # load in data
data_bike['real_time'] <- data_bike$Occurrence_Date 
shpfile <- "toronto-neighbourhoods-master/NEIGHBORHOODS_WGS84_2.shp" # neighbourhood outline data (please change the full filepath to run file)
```

```{r, include=FALSE}
# ARUSAN DATA PREPARATION
bicycles <- read.csv("bicycle-thefts-2014-2019.csv")
wellbeing <- read.csv("wellbeing-toronto.csv")

# Refine data sets
wellbeing[-c(1:3)] <- wellbeing[-c(1:3)] %>% 
  mutate_if(is.character, parse_number)

wellbeing["59", "Neighbourhood"] <- "Danforth East York"
wellbeing["93", "Neighbourhood"] <- "Dovercourt-Wallace Emerson-Junction"
wellbeing["17", "Neighbourhood"] <- "Mimico includes Humber Bay Shores"

bicycles$Neighbourhood <-  str_trim(str_replace_all(bicycles$Neighbourhood, "[()^0-9]", ""))

wellbeing <- wellbeing %>% 
  mutate(Visible.Minority = Visible.Minority.Category - Not.a.Visible.Minority)

# define function to calculate mode
mode <- function(x) {
  u <- unique(x)
  tab <- tabulate(match(x, u))
  u[tab == max(tab)]
}

# merging data
allbikes <- bicycles %>%
  group_by(Neighbourhood) %>% 
  summarise(Thefts = n(),
            Month = mode(Occurrence_Month)[1],
            Premise = mode(Premise_Type)[1],
            Bike = mode(Bike_Type)[1],
            Price = mean(Cost_of_Bike, na.rm = T)) %>% 
  mutate(Percentage = prop.table(Thefts))

neighbourhoods <- merge(allbikes, wellbeing, by="Neighbourhood")

```

```{r}
year_data <- data_bike %>%
  group_by(Occurrence_Year) %>%
  count()

ggplot(year_data, aes(x=Occurrence_Year, y =n)) + geom_bar(stat='identity')
```

```{r}
month_data <- data_bike %>%
  group_by(Occurrence_Year, Occurrence_Month) %>%
  count()

ggplot(month_data, aes(x=Occurrence_Month, y =n, colour = Occurrence_Year, group = Occurrence_Year)) + geom_point() + geom_smooth(se=F)
```